2PC Stream Cipher
tlsnotary/tlsn pull request #199
Opened 2023-02-22 05:19 UTC by sinui0

This PR provides a 2PC stream cipher which is block cipher generic. I've implemented AES, ChaCha should be easy to support later.

**Features**
1. Apply a key stream where one party (leader) provides the plaintext, and both parties receive the authentic ciphertext.
2. Compute additive shares of a key block (used to share the pre-counter block in AES-GCM/ChaCha20-Poly1305)
3. Accepts a transcript sink, where the text + labels for all messages will be pushed
4. The follower uses a dedicated encoder stream for the plaintext labels, and ensures it is free of any padding bits (this gets enforced by the AEAD which includes the plaintext length in the tag/mac).
5. The Leader can prove the plaintext of a ciphertext in ZK.

2023-03-03 07:55 UTC, themighty1 requested changes
nice work,
I have some code comments which I will later add to the review depending on how we resolve the current review.

I didn't comment on the individual `record` flags. The way Im currently seeing it is that there's no need to introduce it as an additional moving part which creates extra friction in understanding the protocol. The User must always record the transcript and the Notary must always use a dedicated stream id. Or maybe there's another reason for `record` which I didn't notice.

Can we use "keystream" everywhere instead of "key stream", in phrases like " a circuit key stream block" it seems like there are 4 nouns together. It will make things simpler if keystream is one word.

2023-03-03 07:55 UTC, themighty1 commented on cipher/stream-cipher/src/follower.rs
> +    async fn build_ctr_share_labels(&mut self) -> Result<KeyBlockLabels, StreamCipherError> {
this is an exact copy of the leader's `build_ctr_share_labels`. we should be able to factor it out into
a standalone fn 
build_ctr_share_labels(labels, encoder, encoder_default_stream_id)

On this note: shouldn't we pass  `encoder_default_stream_id` when instantiating the encoder?

2023-03-06 08:24 UTC, themighty1 commented on cipher/stream-cipher/src/leader.rs
> +                    cipher.input_text(),
i now realize that the encoder stores the offset internally, this is how it advances to the next block.

2023-03-06 08:27 UTC, themighty1 commented on cipher/stream-cipher/src/follower.rs
> +        record: bool,
Why does the Notary need to record those labels? How will they be used?

2023-03-06 08:48 UTC, themighty1 commented on cipher/stream-cipher/src/follower.rs
> +            .verify_and_summarize(
From https://doc.rust-lang.org/book/ch10-02-traits.html
> A trait defines functionality a particular type has and can share with other types

My understanding is that if a method is explained as "depending on configuration, may return true on verification success or may return true but some more steps are needed to complete verification" does not fit "defining functionality".

Anyway, this is a philosophical question which the Rust book does not provide a firm opinion about and so it is better to not expect other devs to look at the code with that philosophy in mind.

In this specific case, I'm worried about the word "verify" and how it is universally understood. We shouldn't call something "verify" if upon return the verification is not completed.

2023-03-06 09:00 UTC, themighty1 commented on cipher/cipher-circuits/src/aes_ctr_masked.rs
> +pub fn aes_ctr_masked() -> Arc<Circuit> {
Seems like a reviewer who dives into code and wants to quickly understand how this circuit will be used in TLSNotary will have extra friction.

I think instead we should take the approach that the stream-cipher is just part of the TLSNotary protocol and not something standalone.

I don't see a problem with adding extra comments like
/// In TLSNotary this circuit is used for...

2023-03-06 09:01 UTC, themighty1 commented
added to my summary comment:
I think we should rename Leader and Follower into Prover and Notary to make this code simpler to follow.

2023-03-08 12:21 UTC, themighty1 approved these changes
ack for now, will have a more thorough review later.

2023-03-09 09:04 UTC, th4s commented on cipher/stream-cipher/src/counter_block.rs
> +    private: bool,
alright let's leave it like this and try to avoid it next time.

2023-03-09 09:05 UTC, th4s commented on cipher/cipher-circuits/src/aes_ctr_masked.rs
> +pub fn aes_ctr_masked() -> Arc<Circuit> {
from my side it's ok :+1:

2023-03-09 11:04 UTC, themighty1 commented on cipher/cipher-circuits/src/aes_ctr_masked.rs
> +pub fn aes_ctr_masked() -> Arc<Circuit> {
resolved

2023-03-09 22:01 UTC, th4s commented
alright, then let's keep it.

2023-03-09 22:02 UTC, merged