Refactor mpc-garble-core
tlsnotary/tlsn pull request #219
Opened 2023-04-18 04:05 UTC by sinui0

This PR greatly simplifies our core garbled circuit types, building on top of the improvements to `mpc-circuits` brought in #212.

# Changes
* Completely documented the public API and added lints
* Serde all the things
* Rewrote the core types for representing encoded values, building on #212 
  * With these changes came immense simplifications to our types for encodings, decodings, label commitments, etc. Many things are now statically enforced by the type system, removing a crap load of boiler plate for data validation.
  * Encoded values are _decoupled_ from the old `GarbledCircuit` type (which no longer exists :pray: ). Values are independent of circuits.
  * The `Label` type is mostly hidden from the public API.
  * Decodings are now size optimal. Eg, the decoding for a `u8` is represented as a `u8`, whereas previously we were sending `Vec<bool>`
* The encoder is now idempotent. I understand the safety concerns for this, but this is a _core_ crate, not to be used be the general public. Structures for managing the state required to prevent duplicate encodings are coming in the `mpc-garble` crate in the following PR.
* Garbled circuit streaming :rocket: Now both the generator and evaluator can execute the circuit concurrently. This was not necessary but didn't take much and I was in the area anyhow.

Needs more tests

2023-04-19 09:56 UTC, th4s requested changes
Awesome :100:, nice PR! I have some comments :)

2023-04-19 09:56 UTC, th4s commented on mpc/garble/mpc-garble-core/src/encoding/value.rs
> +macro_rules! define_decoding {
Same for this macro.

2023-04-19 09:56 UTC, th4s commented on mpc/garble/mpc-garble-core/src/encoding/value.rs
> +            fn compute_hash(block: Block) -> Block {
Can't we use `DomainSeparatedHash` here?

2023-04-19 09:56 UTC, th4s commented on mpc/garble/mpc-garble-core/src/evaluator.rs
> +pub struct Evaluator {
Can we add some description for the fields?

2023-04-19 09:56 UTC, th4s commented on mpc/garble/mpc-garble-core/src/generator.rs
> +impl Iterator for Generator {
I am not sure if it is a good idea to have state-modifying behavior inside an iterator implementation, which has nothing to do with iteration. You feed things into the hasher and modify `gid` while iterating.

In contrast, the evaluator does these things in `evaluate`. Maybe it is better to have a special method which does these things for the generator as well.

2023-04-19 09:56 UTC, th4s commented on mpc/garble/mpc-garble-core/src/lib.rs
> +pub(crate) static CIPHER_FIXED_KEY: [u8; 16] = [69u8; 16];
Can we add a short comment, why it is ok to use a hard-coded encryption key?

2023-04-19 16:14 UTC, th4s commented on mpc/garble/mpc-garble-core/src/encoding/value.rs
> +macro_rules! define_encoded_value {
I am fine with both.

2023-04-19 16:16 UTC, th4s commented on mpc/garble/mpc-garble-core/src/generator.rs
> +impl Iterator for Generator {
I think my thought was, that if the `Generator` is used without iteration somehow, then the hash is wrong.

2023-04-19 16:17 UTC, th4s commented on mpc/garble/mpc-garble-core/src/encoding/mod.rs
> +    pub(crate) fn into_inner(self) -> Block {
I always have to look up the non-trivial case :D

2023-04-19 16:18 UTC, th4s commented on mpc/garble/mpc-garble-core/src/encoding/value.rs
> +macro_rules! define_decoding {
Ok then let's keep it.

2023-04-19 16:22 UTC, th4s commented on mpc/garble/mpc-garble-core/src/generator.rs
> +impl Iterator for Generator {
Hmm I see. Ok then let's keep it and maybe add a note?

2023-04-24 07:41 UTC, themighty1 approved these changes
ACK, gw

2023-04-24 16:09 UTC, th4s approved these changes
:rocket: ack

2023-04-24 16:23 UTC, merged