Refactor share conversion, again.
tlsnotary/tlsn pull request #242
Opened 2023-05-14 23:00 UTC by sinui0

This PR refactors our share conversion crates in a number of ways described below. Note that I avoided making alterations to the protocol algorithms with the exception of the `Mul` impl on `Gf2_128`.

# Changes
- Docs, lints + clippy :paperclip: 
- Renamed some methods for clarity, I hope you agree
- Deprecates the share conversion actor in favor of lightweight Arc + Mutex wrappers found in `mpc-share-conversion/src/converter.rs`
- Simplifies the `Field` trait to no longer have an `Encoding` associated type. This information was moved to the `BlockSerialize` trait in `mpc_core`.
- Adds OT supertraits to provide blanket impls for `Field` types.
- Modifies share conversion traits to receive `&self` instead of `&mut self`, and wrapped internal state in a Mutex to facilitate this.
  - *Note* Concurrent conversion is not actually supported at the moment. To support this we will have to change the way we record to the tape, using a unique ID approach similar to what we do in `mpc-garble`. Trying to use the converters concurrently right now will just result in a tape verification error if a race condition occurred (but not an actual security issue).
- Consolidated the `A2M` and `M2A` functionality into a single instance. Both protocols can be recorded on the same tape. This reduces a lot of boilerplate.
- Updated the `Gf2_128` type to make it easier to reason about, and tweaked `Mul` to match the NIST implementation.
- Updated dependent crates
- Implemented `serde` derives for the protocol messages

2023-05-15 19:23 UTC, th4s approved these changes
Nice :rocket: You now chose an enum approach for `Add` and `Mul` shares. It's very interesting to see the difference considering implementation and API, since we had it generic before. What were your thoughts? I feel that the code gets simpler (which is definitely a big advantage). On the other hand we move a lot from compile-time typesystem checks to runtime. What was your trigger to do this :upside_down_face: ?

2023-05-15 19:23 UTC, th4s commented on mpc/share-conversion/mpc-share-conversion/src/converter.rs
> +    sender: Option<Arc<GilboaSender<F>>>,
If I remember correctly, only one version was called "Gilboa". I think it was M2A from this paper on page 6 https://link.springer.com/content/pdf/10.1007/3-540-48405-1_8.pdf

2023-05-15 19:23 UTC, th4s commented on mpc/share-conversion/mpc-share-conversion/src/converter.rs
> +pub struct ConverterSenderHandle<F: Field, OT> {
Why exactly do we need that?

2023-05-15 19:54 UTC, th4s commented on mpc/share-conversion/mpc-share-conversion-core/src/shares.rs
> +    pub fn ty(&self) -> ShareType {
Ahh ok I did not know about this. I prefer `typ` but fine with the other one, too, if that is some convention.

2023-05-15 19:56 UTC, th4s commented
No concerns. I just wanted to know :) I think the API is nicer now.

2023-05-17 09:12 UTC, themighty1 requested changes

2023-05-17 09:12 UTC, themighty1 commented on mpc/share-conversion/mpc-share-conversion/src/sender.rs
> +        // Send OT shares to the receiver and increment batch counter
"and increment batch counter" is not accurate for this line

2023-05-17 09:12 UTC, themighty1 commented on mpc/share-conversion/mpc-share-conversion/src/tape.rs
> +/// who will check it against her tape to detect any malicious behaviour of the sender.
Can we make an extra note here that rng seed is also revealed by the sender, otherwise it may seems as if tape is all that is needed for the replay.

2023-05-22 18:11 UTC, merged

2023-05-29 08:02 UTC, themighty1 commented
lgtm