Release preparation for workspace `prf`
tlsnotary/tlsn pull request #274
Opened 2023-06-19 10:31 UTC by th4s

- Tidy up manifests
- Improve doc
- Check for panics
- Add tracing

2023-06-23 06:40 UTC, themighty1 requested changes
A general comment:
we don't want to include in the trace any material which would allow a malicious Notary who gets hold of the debug log to construct the full session keys and to decrypt the whole TLS transcript. 

I would suggest that we `skip` absolutely everything (that includes also skipping `inner_state`, `outer_state`). This will make it simpler to reason about: "we just dont log anything from the PRF, so it's impossible for the Notary who gets hold of the logs to glean anything".

Otherwise, we (and also future code auditors) would have to carefully examine whether or not the specific material which we log creates an issue.

2023-06-23 06:40 UTC, themighty1 commented on prf/hmac-sha256-circuits/src/hmac_sha256.rs
> +#[cfg_attr(feature = "tracing", tracing::instrument(level = "trace"))]
Im sure we need to NOT include some of the args into the trace.

2023-06-26 09:23 UTC, th4s commented
I adapted the logging. Now we only log `client_random`, `server_random` and `handshake_hash`.

2023-06-27 08:41 UTC, themighty1 approved these changes
gw!

2023-06-27 08:41 UTC, themighty1 commented on components/prf/hmac-sha256/src/prf.rs
> +        tracing::instrument(level = "debug", skip(self, handshake_hash), err)
for consistency, let's **NOT** skip `handshake_hash` here since we are not skipping it elsewhere

2023-06-27 13:10 UTC, merged