feat: selective disclosure tooling
tlsnotary/tlsn pull request #335
Opened 2023-09-19 00:44 UTC by sinui0

This PR introduces new tooling for selective disclosure of HTTP and JSON data. It focuses on the builder pattern to provide an ergonomic API for committing and proving the two formats. I decided to carve verification out of scope for this PR.

This is a fairly rough first pass at implementing this tooling, I expect implementation details to change but hopefully this initial API makes sense.

# Changes
- Introduces the `tlsn-formats` crate which also adds the `NotarizedHttpSession` type.
- Encapsulate functionality in `tlsn-prover` into the `tls` module.
- Modifies `SubstringsProofBuilder` to depend on `TranscriptCommitments` instead of `SessionData`
- Adds `http` module to `tlsn-prover` which provides `HttpProver` helps the user construct a `NotarizedHttpSession`

2023-10-13 16:29 UTC, th4s reviewed
Nice work :rocket:

I think it is a good and flexible design that commitment and proof builders mutably borrow `TranscriptCommitmentBuilder` and `SubstringProofBuilder` and so to say use their knowledge over the format to drive them.

Have some questions remarks here and there.

2023-10-17 13:28 UTC, themighty1 requested changes
lgtm, some minor things need to be fixed

2023-10-17 13:28 UTC, themighty1 commented on tlsn/tlsn-formats/src/http/proof.rs
> +    pub fn build(self) -> Result<(), HttpProofBuilderError> {
need a doc comment here

2023-10-17 13:28 UTC, themighty1 commented on tlsn/tlsn-core/src/transcript.rs
> +        for range in self
we can introduce `set.intersection()` to make this easier to read

2023-10-17 13:29 UTC, themighty1 approved these changes

2023-10-18 17:52 UTC, th4s commented on tlsn/tlsn-formats/src/http/proof.rs
> +    body_built: bool,
Can we then add a comment?

2023-10-18 18:01 UTC, th4s commented on tlsn/tlsn-prover/src/tls/mod.rs
> +    /// where it can generate commitments to the transcript prior to finalization.
I reread it a few times and it makes sense now. I think I still have to get used to the fact that the default case is having a verifier and no notary.

2023-10-18 18:09 UTC, th4s approved these changes
:+1:

2023-10-18 18:14 UTC, merged