refactor: selective disclosure api
tlsnotary/tlsn pull request #380
Opened 2023-10-31 03:48 UTC by sinui0

This PR redesigns our selective disclosure API, inverting control over the parsed data structures, passing them out to the user instead.

All previous data format structures have been ripped out in favor of re-exporting types from `spansy`, and then leveraging the `ToRangeSet` trait from `tlsn-utils` in the `tlsn-core` API. Users who want to implement their own format types can if they wish, their types only need to implement `ToRangeSet` to integrate with `tlsn-core`.

It introduces two new traits, `HttpCommit` and `JsonCommit` which a user can either implement themselves, or just use our default committer. Both traits provide blanket impls for all the methods, so a user can override something without having to reimplement everything.

This API is by no means final. It will continue to evolve as we introduce new commitment types. There is also room for new abstractions for generating _proofs_ similar to how we do commitments via the `*Commit` traits. For now I've kept that out of scope of this PR and users will have to use the `SubstringsProofBuilder` API directly (which isn't too bad because at least now they can use typed data instead of manually specifying ranges).

2023-10-31 07:45 UTC, themighty1 commented
ack on the concept

2023-10-31 09:44 UTC, rozag commented
Nice! Looking forward to switching to this new API 👍

2023-10-31 13:12 UTC, th4s approved these changes
Yes I think this is a good approach :+1:

2024-02-07 10:22 UTC, themighty1 requested changes
looks good,

can we use the same formatting for method args everywhere in this PR as per https://github.com/tlsnotary/tlsn/blob/dev/CONTRIBUTING.md#function-arguments

/// * `arg1` - The first argument.
(The first letter capitalized and a period at the end)

2024-02-07 10:22 UTC, themighty1 commented on tlsn/tlsn-formats/src/json/commit.rs
> +    /// excluding all values.
```suggestion
    /// excluding all values and separators.
```

2024-02-08 07:51 UTC, themighty1 commented on tlsn/tlsn-formats/src/http/commit.rs
> +        direction: Direction,
ok, the server can be the prover, understood. Then we need to change the doc comment for `enum Direction`. Currently it says     
/// Sent from the prover to the server

2024-02-08 08:14 UTC, themighty1 approved these changes
gw

2024-02-08 08:14 UTC, themighty1 commented on tlsn/tlsn-formats/src/json/commit.rs
> +    /// Commits to a JSON string.
```suggestion
    /// Commits to an unquoted JSON string.
```

2024-02-08 10:21 UTC, th4s approved these changes
:rocket: gw. Very nice API.

2024-02-08 10:21 UTC, th4s commented on tlsn/tlsn-formats/src/json/commit.rs
> +        // separators.
This is probably part of a follow-up PR later?

2024-02-08 21:52 UTC, merged