Use env var for logging filter, remove otel.
tlsnotary/tlsn pull request #422
Opened 2024-02-06 08:42 UTC by yuroitaki

This addresses https://github.com/tlsnotary/tlsn/issues/412

- Switched from using config file to indicate log verbosity level to using RUST_LOG env var which is much more flexible
- Removed opentelemetry setup code which is flooding the logs with `SpanData` struct because it was temporarily setup to export to stdout — we can remove it for now since we're not using any opentelemetry tool yet

2024-02-06 09:20 UTC, heeckhau requested changes

2024-02-06 09:20 UTC, heeckhau commented on notary-server/README.md
> +The default logging of this server is set to `DEBUG` verbosity level for all crates (both internal and external) using tracing crate's [EnvFilter](https://docs.rs/tracing-subscriber/latest/tracing_su
Maybe we should call this section `Logging`?

2024-02-08 02:33 UTC, yuroitaki commented on components/tls/tls-client/src/backend/standard.rs
yep ran cargo fmt and affected them, but have excluded them

2024-02-09 12:14 UTC, yuroitaki commented
By the way @sinui0 @heeckhau please don't merge this first even after all approvals have been obtained when I am away — since there's a format change of the config file, I'd like to change that in our AWS server first before CD kicks in which ll fail otherwise (though that's actually okay since we can manually start the server after, just my preference to correct things before CD fails)

2024-02-09 13:18 UTC, heeckhau approved these changes

2024-02-09 13:18 UTC, heeckhau commented on notary-server/README.md
> +The default logging strategy of this server is set to `DEBUG` verbosity level for the crates that are useful for most debugging scenarios, i.e. using the following filtering logic,
```suggestion
The default logging strategy of this server is set to `DEBUG` verbosity level for the crates that are useful for most debugging scenarios, i.e. using the following filtering logic:
```

2024-02-09 14:20 UTC, merged