refactor(tlsn-examples): update hyper and use http prover
tlsnotary/tlsn pull request #434
Opened 2024-02-09 23:33 UTC by sinui0

This PR updates/simplifies the examples. It depends on both #433 and #432, otherwise the twitter example will fail.

# Changes
1. Bump version of `hyper` to `1.1` and update code to accommodate
2. Factor out some common code into the `tlsn-examples` lib
3. Update the twitter DM example to use `HttpProver` and new selective disclosure API.
4. Update twitter DM to use deferred decryption feature.

2024-02-12 09:40 UTC, th4s approved these changes
:+1:

2024-02-12 10:19 UTC, themighty1 approved these changes

2024-02-12 10:28 UTC, heeckhau requested changes
Great work. The examples look a lot better ❤️ 

However, the Twitter examples fails for me now

2024-02-12 10:28 UTC, heeckhau commented on tlsn/examples/twitter/twitter_dm.rs
> +    prover.commit().unwrap();
This fails for me:
```log
thread 'main' panicked at examples/twitter/twitter_dm.rs:127:21:
called `Result::unwrap()` on an `Err` value: HttpCommitError { idx: None, record_kind: Response, msg: "failed to commit to JSON body", source: Some(JsonCommitError { msg: "failed to commit array excluding values", source: Some(Duplicate(CommitmentId(122))) }) }
```

2024-02-12 23:06 UTC, heeckhau commented
> Rebased to include changes from #432 . @heeckhau merging is blocked on your review, please retry and confirm 🙏
@sinui0  I now get:
```
2024-02-12T23:03:53.833498Z DEBUG finalize: yamux::connection: 06e555ee: new outbound (Stream 06e555ee/63) of (Connection 06e555ee Client (streams 31))    
2024-02-12T23:03:54.614104Z DEBUG twitter_dm: Notarization complete!
thread 'main' panicked at examples/twitter/twitter_dm.rs:177:10:
called `Result::unwrap()` on an `Err` value: MissingCommitment
```

2024-02-13 09:00 UTC, heeckhau approved these changes
👍 Approved

2024-02-13 14:50 UTC, merged