feat: record layer preprocessing
tlsnotary/tlsn pull request #455
Opened 2024-03-12 21:28 UTC by sinui0

Closes #444 

This PR implements MPC preprocessing for the record layer. Specifically, it will pregarble the circuits for encryption up to the configured transcript limit and 256 bytes for decryption for the handshake.

Later we will want to come up with a strategy for preprocessing decryption, keeping in mind that a User may want to decrypt before and after the TLS connection is closed. This interacts with the deferred decryption feature in an annoying way.

2024-03-13 11:23 UTC, th4s approved these changes
Looking good, gw :+1:

2024-03-15 08:26 UTC, themighty1 commented
will review soon.

2024-03-20 10:48 UTC, themighty1 requested changes
gw, some comments and maybe a code change.

2024-03-20 10:48 UTC, themighty1 commented on components/cipher/stream-cipher/src/stream_cipher.rs
> +}
```suggestion
/// A subset of plaintext bytes processed by the stream cipher.
///
/// Note that `Transcript` does not store the actual bytes. Instead, it provides IDs which are
/// assigned to plaintext bytes of the stream cipher.
struct Transcript {
    /// The ID of this transcript.
    id: String,
    /// The ID for the next plaintext byte.
    plaintext: NestedId,
}
```

2024-03-20 10:48 UTC, themighty1 commented on components/cipher/stream-cipher/src/stream_cipher.rs
>      async fn apply_keystream(
```suggestion
    /// Applies the keystream to the provided input text.
    async fn apply_keystream(
```

2024-03-25 06:33 UTC, themighty1 commented on components/cipher/stream-cipher/src/stream_cipher.rs
> +            .verify(&[value], &[expected])
ah, ok, so the `Verify` trait guarantees both authenticity and correctness of the output. I thought it only dealt with authenticity as per its description.
Are you ok if i change the traits description to explicitely mention correctness @sinui0

2024-03-25 07:02 UTC, themighty1 commented on components/cipher/stream-cipher/src/config.rs
> +    Verify,
>  Prove -> only this party has private inputs

That description does not fit here:

https://github.com/tlsnotary/tlsn/blob/8df19a04e5db7e56a742f5e6dff96660d80a783b/components/cipher/stream-cipher/src/keystream.rs#L254-L262

The `key` and `iv` are not private inputs of this party only, they are both parties' private inputs.

@sinui0

2024-03-25 07:08 UTC, themighty1 commented
gw, ACK to merge.
We can continue discussing a more precise type description in this PR.

2024-03-25 07:08 UTC, themighty1 approved these changes

2024-03-25 16:58 UTC, merged