refactor(prf): mpz upgrade
tlsnotary/tlsn pull request #497
Opened 2024-06-12 01:23 UTC by sinui0

This PR updates our `prf` crate to use the new `mpz` API.

*Note*: The exact commit of `mpz` is not settled yet, we will update this prior to release.

# Changes
- A bit of general clean up including making the error type opaque
- Utilizes the preprocessing API from `mpz` to preprocess the prf as much as possible prior to the online phase.
- The PRF verify data was switched to being public, which should cut down on latency due to not needing OTPs.

2024-06-12 10:35 UTC, th4s reviewed
Nice :+1:

Shouldn't we adapt the `Prf` trait to reflect that `cfvd` and `sfvd` are no longer private?

2024-06-12 10:35 UTC, th4s commented on components/prf/hmac-sha256/src/prf.rs
> +            self.thread_0
This is now `thread_0` instead of `thread_1` but it doesn't matter, right?

2024-06-13 08:15 UTC, themighty1 requested changes
gw! some changes may be needed.

2024-06-13 08:15 UTC, themighty1 commented on components/prf/hmac-sha256/src/prf.rs
> +            let mut outputs = self.thread_0.decode(&[sf_vd.vd]).await?;
as above, we need to make sure that `compute_server_finished_vd_private/blind` is now called `compute_server_finished_vd`.

2024-06-14 06:00 UTC, themighty1 approved these changes

2024-06-14 07:47 UTC, merged