Implement matrix transpose
tlsnotary/tlsn pull request #50
Opened 2022-08-03 19:03 UTC by th4s

Adding the matrix transpose algorithm. I open this as a draft, because it isn't yet integrated into OT.

2022-08-05 06:42 UTC, th4s commented
Adapt KOS implementation to support matrix-transpose:
- [ ]  Make sure that OT matrix has a multiple of 32 columns and rows
- [ ] Go from `<Vec<Vec<T>>` matrix representation to `<Vec<T>>`

2022-08-09 18:49 UTC, sinui0 approved these changes
lgtm, nice work

2022-08-10 10:56 UTC, themighty1 requested changes
I ran the tests on nightly with 
cargo test --features "simd-transpose"
 and got an error

error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
   --> /home/default2/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.9/src/atomic.rs:314:6
    |
314 | impl<T: ?Sized + Pointable> Atomic<T> {
    |      ^
...
346 |     pub const fn null() -> Atomic<T> {
    |     -------------------------------- function declared as const here
    |
    = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information
    = help: add `#![feature(const_fn_trait_bound)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `crossbeam-epoch` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

2022-08-10 10:56 UTC, themighty1 commented on matrix-transpose/src/lib.rs
> +    // Check that slice is rectangular
I feel like not everyone is familiar with using & like that. Let's add a comment:
// Check that slice is rectangular, i.e. the number of cells is  a multiple of the number of rows.

2022-08-10 11:15 UTC, th4s commented
Can you repeat with `cargo +nightly -F simd-transpose`? You have to compile with nightly toolchain since `simd-transpose` only works on nightly.

2022-08-10 12:32 UTC, themighty1 approved these changes
well done, ack.

2022-08-10 12:33 UTC, merged