feat(tlsn-wasm): wasm bindings
tlsnotary/tlsn pull request #536
Opened 2024-07-20 04:27 UTC by sinui0

This PR implements WASM bindings for the prover and verifier. Additionally, it provides a custom test runner which handles setting up all the required dependencies to run the integration tests in the browser.

2024-07-23 19:48 UTC, heeckhau requested changes
Awesome. I'm really glad you got this working and tested.

We should either hardcode the ports or use variables everywhere.

2024-07-23 19:48 UTC, heeckhau commented on tlsn/tlsn-wasm/src/tests.rs
> +            "ws://localhost:8080/tcp?addr=localhost%3A8083",
localhost=PROXY_IP
8080=PROXY_PORT
localhost=SERVER_IP
8083=SERVER_PORT

2024-07-24 05:00 UTC, maceip commented
🙇 🦀

2024-07-24 07:26 UTC, heeckhau commented on tlsn/tlsn-wasm/src/tests.rs
> +            "ws://localhost:8080/tcp?addr=localhost%3A8083",
👍  let's move this to a new issue with a "good first issue" label

2024-07-24 08:01 UTC, heeckhau reviewed
Suggested fix for Clippy warning

2024-07-24 08:01 UTC, heeckhau commented on crates/wasm/src/tests.rs
> +    prover
```suggestion
    #[allow(clippy::single_range_in_vec_init)]
    prover
```

2024-07-24 08:01 UTC, heeckhau commented on crates/wasm/src/tests.rs
> +    prover
```suggestion
    #[allow(clippy::single_range_in_vec_init)]
    prover
```

2024-07-24 08:01 UTC, heeckhau approved these changes

2024-07-25 05:04 UTC, th4s approved these changes
Very nice :rocket: :rocket: :rocket:

2024-07-25 05:15 UTC, merged