GC core impl improvements
tlsnotary/tlsn pull request #55
Opened 2022-08-13 00:18 UTC by sinui0

Some things included in the scope of this PR:

- [x] Incorporate interface changes from #51 (will change base to dev after this is merged)
- [x] Add newtypes to enforce safety and consistency invariants
- [x] Reorganize label structs into it's own module
- [x] Incorporate changes into DualEx impl
- [x] Refactor msg types and corresponding conversions

2022-08-15 09:56 UTC, th4s reviewed
:+1: lgtm

2022-08-15 09:56 UTC, th4s commented on mpc-core/src/garble/evaluator.rs
>  pub(crate) fn and_gate<C: BlockCipher<BlockSize = U16> + BlockEncrypt>(
Is this the half-gate method? Can we add a comment?

2022-08-15 09:56 UTC, th4s commented on mpc-core/src/garble/label.rs
> +        let delta = match delta {
Use `unwrap_or_else`?

2022-08-15 09:56 UTC, th4s commented on mpc-core/src/msgs/garble.rs
> +    pub fn from_msg(circ: Arc<Circuit>, msg: GarbledCircuit) -> Result<Self, crate::garble::Error> {
Is this too computation intensive for a `TryFrom` implementation? Does it make sense to break it down into smaller pieces?

2022-08-16 08:55 UTC, th4s commented on mpc-core/src/msgs/garble.rs
> +    pub fn from_msg(circ: Arc<Circuit>, msg: GarbledCircuit) -> Result<Self, crate::garble::Error> {
Hmm now that I see it, I have changed my mind, lol. I agree, it is too clunky, and it does not make sense to create a wrapper type for both structs just to satisfy the `TryFrom` interface. Probably the best to leave it like it is.

2022-08-16 10:26 UTC, themighty1 requested changes
nicely done, left some comments.

2022-08-16 10:26 UTC, themighty1 commented on mpc-core/src/garble/label.rs
> +pub struct SanitizedInputLabels(Vec<WireLabel>);
Could we please have tests which trigger all the error conditions, since this code is security-critical.

2022-08-16 12:21 UTC, th4s approved these changes
nice :rocket:

2022-08-17 00:27 UTC, merged