Do not include git commit timestamp in notary server + use git2 instead of git command + add dirty suffix
tlsnotary/tlsn pull request #643
Opened 2024-10-16 16:49 UTC by heeckhau

There are some problems with the git commit timestamp (GitHub actions has no exact variable for this, it might be different across time zones,...) so I decided to drop this field.

I also used Rust's git2 instead of calling out to a potentially missing git binary.

For local builds, I also added a flag to indicated the build might have local changes (wrt to the commit hash)

2024-10-17 04:33 UTC, yuroitaki requested changes
Great stuff! Though when i built and ran the notary server as docker container locally, the '/info' endpoint returns `(with local changes)` eventhough i never modified anything. Does that happen at your end too?

2024-10-17 04:33 UTC, yuroitaki commented on crates/notary/server/src/domain.rs
> -    /// Current git commit timestamp of notary-server
need to update openapi.yaml too for this api response

2024-10-18 06:50 UTC, heeckhau commented
> Great stuff! Though when i built and ran the notary server as docker container locally, the '/info' endpoint returns `(with local changes)` eventhough i never modified anything. Does that happen at your end too?

It should only add the suffix if there are actual changes. I struggled more than expect on the implementation. If it does not work for you, we may better drop it

2024-10-18 15:38 UTC, maceip commented
lgtm => in rust:slim:

```
# git
sh: 43: git: not found
# cargo run --bin notary-server
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.42s
     Running `target/debug/notary-server`
2024-10-18T15:37:18.026878Z DEBUG main ThreadId(01) notary_server: Server config loaded
```

2024-10-18 15:39 UTC, maceip approved these changes

2024-10-21 05:06 UTC, yuroitaki approved these changes
LGTM!

2024-10-23 06:52 UTC, yuroitaki commented on crates/notary/server/build.rs
> +                // return Err(e.to_string().into());
need this?

2024-10-23 08:29 UTC, merged