DualEx mpc-aio
tlsnotary/tlsn pull request #84
Opened 2022-09-21 23:04 UTC by sinui0

This PR implements dual execution in aio layer. Couple modifications to core crate, moving things around and implementing message types.

2022-09-23 05:09 UTC, themighty1 requested changes

2022-09-23 05:09 UTC, themighty1 commented on mpc-aio/src/protocol/garble/exec/dual.rs
> +        let leader_check = msg.into();
@sinui0 , I don't see the step where Leader's commitment is checked.

2022-09-26 08:17 UTC, themighty1 approved these changes
ACK

2022-09-26 09:40 UTC, th4s approved these changes
ACK

2022-09-26 16:47 UTC, merged