2PC PRF aio
tlsnotary/tlsn pull request #89
Opened 2022-09-29 22:52 UTC by sinui0

This PR implements our 2PC PRF protocol in tls-2pc-aio. It also touches up the core crate, mostly renaming and slightly changing up the interface (should be no change to business logic). Additionally, I added lazy loading for the circuits and benches.

2022-09-30 13:14 UTC, th4s reviewed
Nice work!

2022-10-01 10:20 UTC, th4s commented on tls-2pc-aio/src/prf/circuits/c1.rs
> +        .input(2)
Sounds good :)

2022-10-03 07:28 UTC, themighty1 requested changes
gw

2022-10-03 07:28 UTC, themighty1 commented on tls-2pc-aio/src/prf/mod.rs
> +        let (expected_swk, expected_cwk, expected_siv, expected_civ) =
There must be an error somewhere because the correct return order is cwk, swk, civ, siv

2022-10-03 19:08 UTC, merged